# Generated by Django 6.0.2 on 2026-02-08 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('picture', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('auth_provider', models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('both', 'Both')], default='local', max_length=10)),
                ('email_verified', models.BooleanField(default=False)),
                ('picture_url', models.URLField(blank=True, max_length=500)),
                ('google_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('alpaca_api_key', models.CharField(blank=True, max_length=50)),
                ('_alpaca_secret_key', models.BinaryField(blank=True, db_column='alpaca_secret_key', null=True)),
                ('alpaca_account_id', models.CharField(blank=True, max_length=50)),
                ('alpaca_is_paper', models.BooleanField(default=True)),
                ('alpaca_connected', models.BooleanField(default=False)),
                ('alpaca_connected_at', models.DateTimeField(blank=True, null=True)),
                ('alpaca_last_error', models.TextField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('momentum', 'Momentum'), ('mean_reversion', 'Mean Reversion'), ('contrarian', 'Contrarian'), ('balanced', 'Balanced')], default='balanced', max_length=20)),
                ('analysis_interval_minutes', models.IntegerField(default=15)),
                ('max_position_pct', models.FloatField(default=0.1)),
                ('max_daily_loss_pct', models.FloatField(default=0.03)),
                ('min_confidence', models.FloatField(default=0.7)),
                ('stop_loss_pct', models.FloatField(default=0.05)),
                ('take_profit_pct', models.FloatField(default=0.1)),
                ('email_daily_summary', models.BooleanField(default=True)),
                ('email_trade_alerts', models.BooleanField(default=True)),
                ('email_weekly_report', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('trialing', 'Trialing')], default='active', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'db_table': 'user_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('buying_power', models.DecimalField(decimal_places=2, max_digits=14)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('daily_change', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('daily_change_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_paper', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='portfolio_s_user_id_354a04_idx')],
            },
        ),
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('qty', models.IntegerField()),
                ('avg_entry_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unrealized_plpc', models.DecimalField(decimal_places=4, max_digits=8)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=14)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'position_snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='position_sn_user_id_e8fb57_idx'), models.Index(fields=['symbol'], name='position_sn_symbol_9fde60_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('client_order_id', models.CharField(blank=True, max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(default='market', max_length=20)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('filled_avg_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('filled_qty', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('partially_filled', 'Partially Filled'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('strategy', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='trades_user_id_3708ba_idx'), models.Index(fields=['symbol'], name='trades_symbol_bf741e_idx'), models.Index(fields=['status'], name='trades_status_425b31_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchlist_items',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
