# Generated by Django 4.2 on 2026-02-11 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_alpaca_access_token',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='_alpaca_refresh_token',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='alpaca_oauth_scope',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='alpaca_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
