# Generated by Django 6.0.2 on 2026-02-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_api', '0002_user_alpaca_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='active_indicators',
            field=models.JSONField(default=dict),
        ),
    ]
